services:
  - type: web
    name: algolab-ml
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn App.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0